### ISSUE TITLE
Resulted in Error page after clicking on config settings of the plugin

### ISSUE THREAD

**Issue by ghost** [ulsdevteam/pkp-formHoneypot#11]
Hello @ctgraham,

To let you know when we install honeypot we found a minor bug and fixed it. The error occurs when clicked on config Settings after successfully installed - the settings page will not load instead an error message. Then we looked at php_error log below

The error was:

PHP Warning:  filemtime(): stat failed for plugins/generic/formHoneypot/templatestemplates//settingsForm.tpl in /var/www/html/ojs-3.1.2-4/lib/pkp/classes/template/PKPTemplateResource.inc.php on line 51

So we made that changes below and that fixed the issue.

in file ojs/plugins/generic/formHoneypot/FormHoneypotPlugin.inc.php

changes:

//return parent::getTemplatePath($inCore) . 'templates' . DIRECTORY_SEPARATOR;
return parent::getTemplatePath($inCore) . DIRECTORY_SEPARATOR;

As you can see it is a simple fix. config settings of the plugin will load and works as expected after this fix.

Dung.

**Comment by ctgraham** [comment]
@dunnleaddress , what version of formHoneypot are you using?  Release 1.3.1 should try to address this change in OJS via this code:
https://github.com/ulsdevteam/pkp-formHoneypot/blob/add689b0acd4c2e96f11a586c4fe3f9400a6ffb3/FormHoneypotPlugin.inc.php#L325-L339

**Comment by ghost** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE version SYSTEM "../../../lib/pkp/dtd/pluginVersion.dtd">


<version>
        <application>formHoneypot</application>
        <type>plugins.generic</type>
        <release>1.3.1.0</release>
        <date>2019-10-09</date>
        <sitewide>1</sitewide>
        <lazy-load>1</lazy-load>
        <class>FormHoneypotPlugin</class>
</version>

**Comment by ctgraham** [comment]
So, you modified line 334?  There must be an edge case where the version comparison isn't detecting that OJS is later than 3.1.2.

@alex-wreschnig and I should be able to verify and remediate this so it works whether installed under OJS 3.1.1 or 3.1.2.  We should be able to drop some of this backwards compatibility with the adoption of 3.2, since that will also introduce other changes which aren't intended to be backwards compatible (such as moving locales to .po files).

**Comment by ghost** [comment]
Hi ctgraham, it is line 337.

my Application Version - e.g., OJS 3.1.2.

**Comment by alex-wreschnig** [comment]
Thanks for the link, Clinton.

Hmmmm, this is an interesting edge case. This worked in test! I'll see what I can do. Thanks for reporting this, @dunnleaddress .

**Comment by ctgraham** [comment]
Closing this issue as outdated.
