### ISSUE TITLE
Add nb_NO translation

### ISSUE THREAD

**Issue by asmecher** [ulsdevteam/pkp-formHoneypot#12]
User contribution -- here it is in both .xml format (as contributed) and in .po format (I converted it)...

[locale.po.txt](https://github.com/ulsdevteam/pkp-formHoneypot/files/4360636/locale.po.txt)
[locale.xml.txt](https://github.com/ulsdevteam/pkp-formHoneypot/files/4360637/locale.xml.txt)

**Comment by ctgraham** [comment]
Added; better late than never.
https://github.com/ulsdevteam/pkp-formHoneypot/commit/5c9d1f99463a9375e71a3fb54850b3374e5c40f3
