### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by komir2004** [ulsdevteam/pkp-formHoneypot#15]
Sorry for my ignorance but can't find where can configure the plugin, or, doesn't need to be extra configured, it is working as plug an play

**Comment by ctgraham** [comment]
PKP Plugins are configured in the Website Settings:
https://docs.pkp.sfu.ca/learning-ojs/en/settings-website#plugins
> Click the blue arrow next to the plugin name to reveal links to Delete, Upgrade, or Configure settings for the plugin.
