### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by meulop** [ulsdevteam/pkp-formHoneypot#19]
I'm trying to configure this plugin on an OJS server running PHP8 (as 7 is entirely unsupported now) and hitting a number of issues in FormHoneypotSettingsForm.inc.php.

First are two methods that don't match the method signature of the parent class - previously this was a warning but is now fatal:
`PHP Fatal error:  Declaration of FormHoneypotSettingsForm::fetch($request) must be compatible with Form::fetch($request, $template = null, $display = false) in /var/www/ojs-3.3.0-11/plugins/generic/formHoneypot/FormHoneypotSettingsForm.
inc.php on line 65`
`PHP Fatal error:  Declaration of FormHoneypotSettingsForm::execute() must be compatible with Form::execute(...$functionArgs) in /var/www/ojs-3.3.0-11/plugins/generic/formHoneypot/FormHoneypotSettingsForm.inc.php on line 81`

Then in __construct there are two uses of create_function(), which has been removed from PHP 8.0 in favour of anonymous functions:
`PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /var/www/ojs-3.3.0-11/plugins/generic/formHoneypot/FormHoneypotSettingsForm.inc.php:44`

**Comment by wopsononock** [comment]
Addressed in https://github.com/ulsdevteam/pkp-formHoneypot/releases/tag/v1.4.0-2
