### ISSUE TITLE
Form Honeypot Plugin doesn't work in OJS 3.3.0.15

### ISSUE THREAD

**Issue by juanCure** [ulsdevteam/pkp-formHoneypot#22]
Hi, I tried to use this plugin in an OJS 3.3.0.15 but I couldn´t make it work. I get the message "Your registration has been blocked". 

This is my environment:

O.S Centos 7
PHP 7.4.33
MySQL 8.0.36
Apache 2.4.57
Version of OJS: 3.3.0.15
Theme: HealthSciences
Version of FormHoneyPot: 1.4.0.1

I didn't find some error message in my Apache/PHP logs.

![your_registration_has_been_blocked](https://github.com/ulsdevteam/pkp-formHoneypot/assets/1661533/88d198e2-2923-486e-81a4-ead2eff9ba15)

I have set as minimum time 10 seconds and as maximum time 180 seconds.

**Comment by ctgraham** [comment]
With your configuration, this message would be intended if the form was completed in less that 10 seconds or in longer that 180 seconds.

The timing of the form starts at the display of the registration page.  Note that navigating away from the form and then back again doesn't stop or restart the timer.

Reading the code, I suspect that it might be possible to permanently trip the honeypot's timer if your browser holds on to the same session cookie for an extended period of time.  If you clear your session cookies for the site, does this allow for registration?

**Comment by juanCure** [comment]
Thanks @ctgraham for your quick answer, I have deleted the sessions using the link Expire User Sessions in the Administrative Functions inside OJS, and after that I have gotten a new user registration.

**Comment by ctgraham** [comment]
On the one hand, this would be a feature if someone was using the same session to repeatedly submit new registrations.  The upper time limit would block all subsequent submissions.

On the other hand, if someone browses to the registration page, and then navigates away, and then comes back later, their request will be "permanently" blocked, which seems undesirable.

An ideal resolution would tie the form timing to the CSRF token; a quick resolution could be to clear the timer after blocking the long registration attempt.

**Comment by juanCure** [comment]
@ctgraham thanks for your tips, I have some doubts:

The requirements  that you mentioned are supposed to be aggregated in a future version? 
Is it secure to use this plugin on OJS 3.3.0.15?
