### ISSUE TITLE
doesn't work in OJS-3.1.2?

### ISSUE THREAD

**Issue by rvdb** [ulsdevteam/pkp-formHoneypot#3]
I realize the docs state that formHoneypot works for OJS-3.1.x, but I'm wondering whether it is supposed to work on OJS-3.1.2 as well?

When I try it on an OJS-3.1.2 installation, there seem to be troubles with paths of plugin files, when trying to access the plugin settings via the website (at least, I found a `/templatestemplates/` path fragment in following log snippet, which suggests something goes wrong in path construction):

    [Wed Apr 24 13:15:02 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr: PHP Warning:  Declaration of FormHoneypotSettingsForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in /var/www/vhosts/domain/sites/test.journal/OJS-3.1.2/plugins/generic/formHoneypot/FormHoneypotSettingsForm.inc.php on line 0, referer: http://test.journal/index.php/OJS-3.1.2/management/settings/website
    [Wed Apr 24 13:15:02 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr: PHP Warning:  filemtime(): stat failed for lib/pkp/templates/plugins/generic/formHoneypot/templatestemplates/settingsForm.tpl in /var/www/vhosts/domain/sites/test.journal/OJS-3.1.2/lib/pkp/classes/template/PKPTemplateResource.inc.php on line 51, referer: http://test.journal/index.php/OJS-3.1.2/management/settings/website
    [Wed Apr 24 13:15:02 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr: PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'app:plugins/generic/formHoneypot/templatestemplates/settingsForm.tpl' <-- , referer: http://test.journal/index.php/OJS-3.1.2/management/settings/website
    [Wed Apr 24 13:15:02 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr:   thrown in /var/www/vhosts/domain/sites/test.journal/OJS-3.1.2/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195, referer: http://test.journal/index.php/OJS-3.1.2/management/settings/website

When accessing the registration form with the plugin enabled, a blank page is returned, with following log entries:

    [Wed Apr 24 13:11:39 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr: PHP Warning:  Declaration of RegistrationHandler::validate($request) should be compatible with PKPHandler::validate($requiredContexts = NULL, $request = NULL) in /var/www/vhosts/domain/sites/test.journal/OJS-3.1.2/lib/pkp/pages/user/RegistrationHandler.inc.php on line 19, referer: http://test.journal/
    [Wed Apr 24 13:11:39 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr: PHP Warning:  Declaration of RegistrationForm::validate() should be compatible with Form::validate($callHooks = true) in /var/www/vhosts/domain/sites/test.journal/OJS-3.1.2/lib/pkp/classes/user/form/RegistrationForm.inc.php on line 21, referer: http://test.journal/
    [Wed Apr 24 13:11:39 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr: PHP Fatal error:  Uncaught  --> Smarty: undefined extension class 'Smarty_Internal_Method_Register_Outputfilter' <-- , referer: http://test.journal/
    [Wed Apr 24 13:11:39 2019] [warn] [client 78.22.120.143] mod_fcgid: stderr:   thrown in /var/www/vhosts/domain/sites/test.journal/OJS-3.1.2/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_undefined.php on line 62, referer: http://test.journal/

**Comment by ctgraham** [comment]
OJS 3.1.2 made some substantial changes to the templating system, and this plugin is not yet compatible with these changes.  We are planning on making it work with 3.1.2.

**Comment by alex-wreschnig** [comment]
Hi rvdb,

With [the latest release](https://github.com/ulsdevteam/pkp-formHoneypot/releases/tag/v1.3.0-0), we've added 3.1.2. (And some 3.2 support, although that's not done baking yet--so there may be further compatibility-breaking changes added before they're done.) It's been pretty well tested but if you find problems don't hesitate to report!

**Comment by rvdb** [comment]
Hi @alex-wreschnig , many thanks for notifying me about the new release! Not to speak of the release itself: seems to work like a charm on my OJS-3.1.2.0 install. 

I've added a Dutch translation in this PR: https://github.com/ulsdevteam/pkp-formHoneypot/pull/8.
