### ISSUE TITLE
Bad variable reference

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-formHoneypot#5]
https://github.com/ulsdevteam/pkp-formHoneypot/blob/7214d03d7ac047570d0a888e93bc0559ebb8528d/FormHoneypotPlugin.inc.php#L72

`element` here should be `$element`.

**Comment by ctgraham** [comment]
But on the other hand, `$element` is not defined outside of the `true` branch of the `if`:
https://github.com/ulsdevteam/pkp-formHoneypot/blob/7214d03d7ac047570d0a888e93bc0559ebb8528d/FormHoneypotPlugin.inc.php#L48-L52

**Comment by ctgraham** [comment]
I think all of this should be handled in the Settings form, not the Plugin registration.
https://github.com/ulsdevteam/pkp-formHoneypot/blob/7214d03d7ac047570d0a888e93bc0559ebb8528d/FormHoneypotPlugin.inc.php#L66-L75

**Comment by alex-wreschnig** [comment]
This commit was merged and squashed, so the issue should be resolved in master.
