### ISSUE TITLE
Use Version::compare() rather than string comparison

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-formHoneypot#6]
c.f. https://github.com/pkp/pkp-lib/blob/756bb61da00a7fb51313e762b8db1c4d736c7da0/classes/site/Version.inc.php#L50-L55

vs. 
https://github.com/ulsdevteam/pkp-formHoneypot/blob/ced4331cd5d2be24811904d719b50750b40bf1f8/FormHoneypotPlugin.inc.php#L138
https://github.com/ulsdevteam/pkp-formHoneypot/blob/ced4331cd5d2be24811904d719b50750b40bf1f8/FormHoneypotPlugin.inc.php#L310
https://github.com/ulsdevteam/pkp-formHoneypot/blob/ced4331cd5d2be24811904d719b50750b40bf1f8/FormHoneypotPlugin.inc.php#L336
https://github.com/ulsdevteam/pkp-formHoneypot/blob/ced4331cd5d2be24811904d719b50750b40bf1f8/FormHoneypotPlugin.inc.php#L388
etc.

**Comment by alex-wreschnig** [comment]
Thanks for the pointer, Clinton! Looks like that method is pretty broadly available. Closing this out.
